# This Makefile is used to compile and upload the code to the Arduino via
# Make, instead of using the IDE.
#
# The user should replace ARDUINO_PORT and the path to Arduino.mk for the
# rigth values if this Makefile is going to be used.
#
# Source code can be downloaded from:
# 	https://github.com/sudar/Arduino-Makefile

ARDMK_DIR    = $(HOME)/work/arduino/Arduino-Makefile
BOARD_TAG    = arduino_due_x
ARCHITECTURE = sam
ARDUINO_LIBS = DueFlashStorage Time AstroLib AccelStepper
ARDUINO_PORT = /dev/ttyACM0
ARDUINO_SKETCHBOOK = .

include $(ARDMK_DIR)/Sam.mk

GDB=$(AVR_TOOLS_DIR)/bin/arm-none-eabi-gdb

openocd:
	openocd -f interface/buspirate.cfg -f target/at91sam3ax_8x.cfg -f arduino-due.cfg

gdb:
	$(GDB) -x gdb.cmd Blink.ino.elf

format:
	astyle --style=stroustrup -p -c -s4 *.cpp *.h *.ino
